version: "3"
services: 
  account-service:
    build: ./services/account-service
    volumes:
      - ./services/account-service:/usr/src/app
    ports: 
      - 50000:80
  phpweb-service:
    build: ./services/phpweb-service
    volumes: 
      - ./services/phpweb-service:/var/www/html
    ports:
      - 80:80
    depends_on: 
      - account-service
      - stock-service
  stock-service:
    build: ./services/stock-service
    volumes:
      - ./services/stock-service:/usr/src/app
    ports:
      - 50003:80